check dir

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -39,6 +39,13 @@ jobs:
           ghcr.io/${{ github.repository_owner }}/quarto-render:latest \
           quarto render thesis.qmd
 
+      - name: Check if _site directory exists
+        run: |
+          if [ ! -d "./VK/thesis/_site" ]; then
+            echo "_site directory does not exist. Rendering failed."
+            exit 1
+          fi
+
       - name: Deploy Thesis to GitHub Pages
         uses: peaceiris/actions-gh-pages@v4
         with:
